/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   api-candidates-dialog.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {PolymerElement} from '@polymer/polymer/polymer-element.js';

import {mixinBehaviors} from '@polymer/polymer/lib/legacy/class.js';

import {NeonAnimationRunnerBehavior} from '@polymer/neon-animation/neon-animation-runner-behavior.js';

import {PaperDialogBehavior} from '@polymer/paper-dialog-behavior/paper-dialog-behavior.js';

import {html} from '@polymer/polymer/lib/utils/html-tag.js';

declare namespace ApiElements {

  /**
   * `api-candidates-dialog`
   *
   * A dialog to select API main file from API zip package.
   *
   * API components uses this component to render a dialog
   *
   * ## Styling
   *
   * `<api-candidates-dialog>` provides the following custom properties and mixins for styling:
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--api-candidates-dialog` | Mixin applied to this elment | `{}`
   */
  class ApiCandidatesDialog {
    candidates: any[]|null|undefined;
    selected: string|null|undefined;
    readonly hasSelection: boolean|null|undefined;
    connectedCallback(): void;
    disconnectedCallback(): void;
    _renderOpened(): void;
    _renderClosed(): void;
    _onNeonAnimationFinish(): void;
    _computeHasSelection(selection: any): any;
    _selectHandler(e: any): void;
    _clearPromises(): void;
    _acceptSelection(): void;
    _closeHandler(e: any): void;
  }
}

declare global {

  interface HTMLElementTagNameMap {
    "api-candidates-dialog": ApiElements.ApiCandidatesDialog;
  }
}
