/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   api-candidates-dialog.html
 */

/// <reference path="../polymer/types/polymer-element.d.ts" />
/// <reference path="../polymer/types/lib/legacy/class.d.ts" />
/// <reference path="../neon-animation/neon-animation-runner-behavior.d.ts" />
/// <reference path="../paper-dialog-behavior/paper-dialog-behavior.d.ts" />
/// <reference path="../iron-flex-layout/iron-flex-layout.d.ts" />
/// <reference path="../paper-styles/shadow.d.ts" />
/// <reference path="../paper-button/paper-button.d.ts" />
/// <reference path="../paper-item/paper-item.d.ts" />
/// <reference path="../paper-listbox/paper-listbox.d.ts" />

declare namespace ApiElements {

  /**
   * `api-candidates-dialog`
   *
   * A dialog to select API main file from API zip package.
   *
   * API components uses this component to render a dialog
   *
   * ## Styling
   *
   * `<api-candidates-dialog>` provides the following custom properties and mixins for styling:
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--api-candidates-dialog` | Mixin applied to this elment | `{}`
   */
  class ApiCandidatesDialog {
    candidates: any[]|null|undefined;
    selected: string|null|undefined;
    readonly hasSelection: boolean|null|undefined;
    connectedCallback(): void;
    disconnectedCallback(): void;
    _renderOpened(): void;
    _renderClosed(): void;
    _onNeonAnimationFinish(): void;
    _computeHasSelection(selection: any): any;
    _selectHandler(e: any): void;
    _clearPromises(): void;
    _acceptSelection(): void;
    _closeHandler(e: any): void;
  }
}

interface HTMLElementTagNameMap {
  "api-candidates-dialog": ApiElements.ApiCandidatesDialog;
}
